NAV_ITEMS = [
    {
        "slug": "operacion",
        "label": "Operación",
        "href": "/operacion/",
        "dropdown": {
            "columns": [
                {
                    "title": "Gestión operativa",
                    "links": [
                        {"label": "Inventarios", "href": "/operacion/inventarios/"},
                        {"label": "Compras y proveedores", "href": "/operacion/compras-y-proveedores/"},
                        {"label": "Logística y almacenes", "href": "/operacion/logistica-y-almacenes/"},
                    ],
                },
            ],
            "aside_title": "Operación conectada",
            "aside_text": "Controla inventarios, compras y almacenes desde un mismo flujo operativo.",
        },
    },
    {
        "slug": "comercial",
        "label": "Comercial",
        "href": "/comercial/",
        "dropdown": {
            "columns": [
                {
                    "title": "Gestión comercial",
                    "links": [
                        {"label": "Ventas y clientes", "href": "/comercial/ventas-y-clientes/"},
                        {"label": "Contratos de retainer", "href": "/comercial/contratos-de-retainer/"},
                    ],
                },
            ],
            "aside_title": "Relaciones comerciales",
            "aside_text": "Centraliza ventas, clientes y contratos para dar seguimiento a cada oportunidad.",
        },
    },
    {
        "slug": "finanzas",
        "label": "Finanzas",
        "href": "/finanzas/",
        "dropdown": {
            "columns": [
                {
                    "title": "Gestión financiera",
                    "links": [
                        {"label": "Finanzas", "href": "/finanzas/"},
                        {"label": "Cuentas por pagar", "href": "/finanzas/cuentas-por-pagar/"},
                        {"label": "Cuentas por cobrar", "href": "/finanzas/cuentas-por-cobrar/"},
                        {"label": "Bancos", "href": "/finanzas/bancos/"},
                        {"label": "CFDI 4.0 en Majjun ERP", "href": "/finanzas/cfdi-4-0-en-majjun-erp/"},
                    ],
                },
            ],
            "aside_title": "Visibilidad financiera",
            "aside_text": "Administra cuentas, bancos y CFDI con información financiera centralizada.",
        },
    },
    {
        "slug": "automatizacion",
        "label": "Automatización",
        "href": "/automatizacion/",
        "dropdown": {
            "columns": [
                {
                    "title": "Inteligencia artificial",
                    "links": [
                        {"label": "IA en Majjun ERP", "href": "/automatizacion/ia-en-majjun-erp/"},
                    ],
                },
            ],
            "aside_title": "Automatización inteligente",
            "aside_text": "Usa IA para agilizar tareas y convertir datos operativos en acciones.",
        },
    },
]

SECTION_TEMPLATES = {
    "features": "pages/sections/features.html",
    "finance_accounting": "pages/sections/finance_ledger.html",
    "banks_finance": "pages/sections/finance_accounting.html",
    "accounts_receivable": "pages/sections/finance_accounting.html",
    "cfdi_guide": "pages/sections/finance_accounting.html",
    "ai_guide": "pages/sections/finance_accounting.html",
    "sales_customers": "pages/sections/sales_customers.html",
    "retainer_contracts": "pages/sections/retainer_contracts.html",
    "accounts_payable": "pages/sections/accounts_payable.html",
    "purchases_suppliers": "pages/sections/purchases_suppliers.html",
    "logistics_warehouses": "pages/sections/logistics_warehouses.html",
    "segments": "pages/sections/segments.html",
    "inventarios": "pages/sections/inventarios.html",
    "resources": "pages/sections/resources.html",
    "pricing": "pages/sections/pricing_skeleton.html",
    "support": "pages/sections/support.html",
}

PAGE_CONTENT = {
    "apps": {
        "id": "modules",
        "title": "Features that keep every invoice, item and ledger entry connected.",
        "description": "Majjun ERP organiza facturacion, compras, inventario, finanzas y auditoria en una sola plataforma cloud para equipos que necesitan control sin friccion.",
        "items": [
            {
                "initial": "AI",
                "color": "#1d4ed8",
                "title": "AI Sales Assistance",
                "description": "Crea facturas, prepara seguimientos y consulta ventas con lenguaje natural sin perder control del flujo comercial.",
                "features": [
                    "Facturas sugeridas desde instrucciones simples",
                    "Alertas de cobranza y clientes prioritarios",
                    "Acciones pendientes antes de cerrar el dia",
                ],
                "cta_label": "Ver asistencia IA",
                "cta_href": "/facturacion/",
            },
            {
                "initial": "FR",
                "color": "#0284c7",
                "title": "Finance & Reporting",
                "description": "Conecta ingresos, egresos, cuentas contables y reportes para entender margen, caja y desempeno por periodo.",
                "features": [
                    "P&L mensual listo para exportar",
                    "Libro mayor y cuentas contables",
                    "Indicadores para direccion y administracion",
                ],
            },
            {
                "initial": "PF",
                "color": "#3b82f6",
                "title": "Procurement Flow",
                "description": "Ordenes de compra, proveedores, vencimientos y gastos conectados con inventario y contabilidad.",
                "features": [
                    "Compras por proveedor con trazabilidad",
                    "Vencimientos y pagos por programar",
                    "XML y comprobantes ligados al gasto",
                ],
                "cta_label": "Explorar operacion",
                "cta_href": "/plataforma/",
            },
            {
                "initial": "GL",
                "color": "#475569",
                "title": "General Ledger & Audit Trail",
                "description": "Registra movimientos contables y deja evidencia clara de usuarios, cambios y documentos relacionados.",
                "features": [
                    "Asientos manuales y ajustes controlados",
                    "Historial por factura, pago y articulo",
                    "Auditoria para equipos administrativos",
                ],
            },
        ],
    },
    "platform": {
        "id": "platform",
        "eyebrow": "AI spotlight",
        "title": "Ask Majjun to create, explain and prepare work across the ERP.",
        "description": "El asistente entiende tareas de ventas, finanzas y compras para convertir instrucciones en borradores, reportes y sugerencias revisables.",
        "features": [
            {
                "number": "1",
                "title": "Create operational records",
                "description": "Pide una factura, gasto o pedido en lenguaje natural y Majjun prepara el borrador con datos clave.",
            },
            {
                "number": "2",
                "title": "Explain financial signals",
                "description": "Consulta ventas, margen, cobranza o P&L sin construir reportes desde cero.",
            },
            {
                "number": "3",
                "title": "Suggest taxes and next steps",
                "description": "Recibe IVA, categorias y acciones sugeridas antes de timbrar, comprar o contabilizar.",
            },
        ],
        "purchase_note": "La IA prepara trabajo, pero tu equipo revisa y aprueba antes de afectar facturas, inventario o contabilidad.",
        "purchase_cta": "See it in action",
        "workflow": [
            {"key": "ASK", "title": "Create invoice for Acme Inc.", "description": "$4,500 services with CFDI data", "status": "Prompt"},
            {"key": "TAX", "title": "Suggested tax: IVA 16%", "description": "Majjun proposes tax treatment before stamping", "status": "Review"},
            {"key": "P&L", "title": "Run this month's P&L report", "description": "Revenue, costs and net income prepared", "status": "Ready"},
            {"key": "PDF", "title": "Export report package", "description": "Share PDF with finance or leadership", "status": "Done"},
        ],
    },
    "billing": {
        "id": "finance",
        "title": "CFDI 4.0 invoicing built into the same operating flow.",
        "description": "Emite facturas, complementos de pago y notas de credito desde Majjun ERP, con datos fiscales y paquetes de timbres conectados a tus ventas.",
        "calculator_title": "Invoice preview",
        "features": [
            {
                "title": "Datos fiscales listos",
                "description": "RFC, regimen y codigo postal fiscal visibles para que puedas timbrar sin rechazos por datos maestros incompletos.",
            },
            {
                "title": "CSD, PAC y timbres",
                "description": "Certificados, credenciales y paquetes de timbres preparados para emitir CFDI oficiales desde el flujo de venta.",
            },
            {
                "title": "Payment complements",
                "description": "Forma de pago, moneda y tipo de cambio preparados para que puedas cumplir cuando tus clientes pagan en parcialidades.",
            },
            {
                "title": "SAT cancellation flow",
                "description": "Motivos de cancelacion y UUID de sustitucion integrados para que puedas corregir facturas sin salir del sistema.",
            },
        ],
    },
    "features": {
        "id": "features",
        "eyebrow": "Majjun para equipos operativos",
        "title": "Convierte ventas, compras e inventario en una operacion proactiva y conectada.",
        "description": "",
        "trust_text": "Equipos de comercio, distribucion y servicios ya operan con Majjun ERP",
        "trust_logos": ["Retail", "Servicios", "Distribucion", "B2B", "eCommerce"],
        "solutions_title": "Soluciones por frente operativo",
        "items": [
            {
                "initial": "IN",
                "title": "Inventarios",
                "description": "Administra productos, controla existencias en tiempo real y gestiona kits de venta con trazabilidad.",
                "cta_href": "/operacion/inventarios/",
            },
            {
                "initial": "CP",
                "title": "Compras y proveedores",
                "description": "Organiza proveedores, solicitudes, ordenes de compra y recepciones con recomendaciones inteligentes de reorden.",
                "cta_href": "/operacion/compras-y-proveedores/",
            },
            {
                "initial": "LA",
                "title": "Logística y almacenes",
                "description": "Controla ubicaciones, transferencias, ensamblajes y reposicion para mover mercancia con precision.",
                "cta_href": "/operacion/logistica-y-almacenes/",
            },
        ],
        "ai_title": "IA integrada en los flujos",
        "ai_points": [
            "Resuelve tareas repetitivas con asistentes y reglas.",
            "Prioriza alertas de stock, cobranza y vencimientos.",
            "Sugiere acciones antes de que aparezcan cuellos de botella.",
        ],
        "impact_title": "Resultados que se miden",
        "impact_metrics": [
            {"value": "40%", "label": "menos captura manual", "count": 40, "suffix": "%"},
            {"value": "2x", "label": "mas velocidad en cierre operativo", "count": 2, "suffix": "x"},
            {"value": "24/7", "label": "visibilidad de ventas y stock"},
        ],
        "final_ctas": [
            {"title": "Prueba guiada", "desc": "Activa una prueba con datos demo para ver procesos reales.", "cta": "Probar gratis"},
            {"title": "Demo con experto", "desc": "Revisamos tu operacion y armamos el flujo ideal por area.", "cta": "Agendar demo"},
            {"title": "Recursos", "desc": "Consulta guias de implementacion por modulo y rol.", "cta": "Ver recursos"},
        ],
    },
    "finance_accounting": {
        "id": "finance-accounting",
        "eyebrow": "Gestion financiera",
        "title": "Guia de Finanzas y Contabilidad en Majjun ERP",
        "description": "Organiza tus cuentas, registra ajustes, configura impuestos y consulta reportes clave para entender con claridad cuanto dinero esta ganando tu empresa.",
        "sections": [
            {
                "short_title": "Catalogo de Cuentas",
                "title": "1. Construye un Catalogo de Cuentas ordenado",
                "intro": "Antes de registrar operaciones, define una estructura que represente como se mueve el dinero en tu empresa. El Catalogo de Cuentas es la lista maestra de tus categorias financieras.",
                "route": "Finanzas > Catalogo de Cuentas",
                "points": [
                    "Las cuentas de resumen agrupan informacion. Por ejemplo, Activos Circulantes puede reunir varias cuentas relacionadas.",
                    "Las cuentas contabilizables reciben los movimientos reales de dinero. Caja Chica es un ejemplo habitual.",
                    "Marca Es Contabilizable cuando necesites usar una cuenta en tus registros.",
                    "Crea niveles jerarquicos para que los reportes avancen de lo general a lo particular y sean faciles de interpretar.",
                ],
                "tip": "Una estructura clara desde el inicio facilita el registro diario y evita tener que reorganizar reportes despues.",
            },
            {
                "short_title": "Asientos de Diario",
                "title": "2. Registra ajustes con Asientos de Diario",
                "intro": "Usa los Asientos de Diario para movimientos que no provienen de facturas, como depreciaciones, ajustes contables o cierres de mes.",
                "route": "Finanzas > Asientos de Diario",
                "points": [
                    "Crea un nuevo asiento y escribe una descripcion clara, por ejemplo Ajuste de renta anticipada.",
                    "Comprueba la regla principal antes de continuar: la suma de debitos debe ser igual a la suma de creditos.",
                    "Guarda como borrador si todavia necesitas revisar datos o solicitar una validacion.",
                    "Al contabilizar, el asiento impacta los reportes y ya no debe editarse directamente.",
                ],
                "tip": "Usa descripciones especificas para que cada ajuste sea facil de reconocer durante una revision.",
            },
            {
                "short_title": "Impuestos",
                "title": "3. Configura tasas y codigos de impuestos",
                "intro": "Majjun ERP separa las tasas y los codigos de impuestos para que puedas adaptar el calculo a las necesidades de cada operacion.",
                "routes": [
                    "Finanzas > Tasas de Impuestos",
                    "Finanzas > Codigos de Impuestos",
                ],
                "points": [
                    "Las tasas definen porcentajes individuales, como IVA 16%, y pueden configurarse como normales o de retencion.",
                    "Los codigos permiten agrupar una o mas tasas para aplicarlas juntas.",
                    "En modo paralelo, cada impuesto se calcula por separado sobre el monto base.",
                    "En modo secuencial, cada calculo considera el resultado anterior; es util para impuestos compuestos.",
                    "Prueba un monto en la vista previa, por ejemplo $100, para verificar el resultado antes de usar la configuracion.",
                ],
                "tip": "Valida cada codigo en la vista previa antes de aplicarlo a operaciones reales.",
            },
            {
                "short_title": "Correcciones",
                "title": "4. Corrige sin perder trazabilidad",
                "intro": "En contabilidad, la informacion no se borra: se corrige. Asi mantienes un historial transparente de cada cambio y su motivo.",
                "points": [
                    "Una reversion crea un asiento espejo que anula el impacto de una poliza incorrecta.",
                    "Una correccion revierte la poliza anterior y genera un nuevo borrador con los mismos datos.",
                    "Edita el nuevo borrador, revisa el ajuste y vuelve a contabilizar cuando la informacion sea correcta.",
                ],
                "tip": "Este proceso conserva la evidencia de lo ocurrido y facilita auditorias o revisiones posteriores.",
            },
            {
                "short_title": "Reportes",
                "title": "5. Interpreta el resultado real de tu negocio",
                "intro": "Los reportes financieros convierten los registros diarios en informacion util para decidir con mayor certeza.",
                "points": [
                    "Estado de Resultados: consulta la utilidad o perdida de la empresa en un rango de fechas.",
                    "Balance General: revisa activos, pasivos y patrimonio a una fecha de corte.",
                    "Estado de Flujo de Efectivo: identifica de donde vino el dinero y en que se uso, separado por operacion, inversion y financiamiento.",
                    "Informes Programados: configura envios automaticos, como recibir un reporte cada lunes por correo.",
                ],
                "tip": "Revisa estos reportes con una frecuencia definida para detectar cambios y actuar a tiempo.",
            },
        ],
        "cta_title": "Controla tus finanzas con mayor claridad",
        "cta_description": "Mantén tus cuentas, impuestos y reportes en un solo lugar, sin perder trazabilidad.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "banks_finance": {
        "id": "banks-finance",
        "eyebrow": "Control bancario",
        "title": "Guía de Bancos y Finanzas en Majjun ERP",
        "description": "Conecta tus cuentas bancarias reales con la contabilidad de la empresa, registra movimientos directos y comprueba que los saldos del sistema coincidan con tus estados de cuenta.",
        "sections": [
            {
                "short_title": "Cuentas bancarias",
                "title": "1. Configura tus cuentas bancarias",
                "intro": "Antes de registrar cobros, pagos o movimientos directos, da de alta cada cuenta bancaria para relacionarla correctamente con la contabilidad.",
                "route": "Finanzas > Bancos",
                "points": [
                    "Crea un nuevo banco y asigna un nombre fácil de reconocer, por ejemplo Banorte Operativa.",
                    "Selecciona la moneda y captura el número de cuenta oficial.",
                    "Relaciona la Cuenta GL o cuenta contable correspondiente, como 102.01 - Bancos Nacionales.",
                    "La cuenta contable vinculada permite que los movimientos bancarios se registren automáticamente en contabilidad.",
                    "Captura el saldo inicial para comenzar con una base correcta.",
                    "Al guardar, la cuenta queda disponible para pagos, cobros, transacciones y conciliaciones.",
                ],
                "tip": "Confirma la moneda, el número de cuenta y la Cuenta GL antes de comenzar a registrar movimientos.",
            },
            {
                "short_title": "Movimientos directos",
                "title": "2. Registra depósitos, retiros y ajustes",
                "intro": "Algunos movimientos no provienen de una factura de venta o compra. Registra directamente comisiones bancarias, intereses ganados, ajustes y cargos especiales para mantener saldos y contabilidad completos.",
                "route": "Finanzas > Transacciones Bancarias",
                "points": [
                    "Crea una nueva transacción y selecciona la cuenta bancaria y la fecha del movimiento.",
                    "Elige Depósito para una entrada de dinero o Retiro para una salida.",
                    "En las líneas de transacción, selecciona la cuenta contable que explica el movimiento.",
                    "Para una comisión bancaria, por ejemplo, puedes utilizar la cuenta Gastos Financieros.",
                    "Guarda como borrador cuando necesites revisar los datos antes de confirmarlos.",
                    "Al contabilizar, se actualizan tanto el saldo bancario como los registros contables.",
                ],
                "tip": "Describe cada movimiento con claridad para facilitar su revisión durante la conciliación.",
            },
            {
                "short_title": "Conciliación",
                "title": "3. Concilia el estado de cuenta con Majjun ERP",
                "intro": "La conciliación compara lo reportado por el banco con los movimientos registrados por tu empresa para detectar diferencias, omisiones o cargos pendientes.",
                "route": "Finanzas > Bancos > Seleccionar cuenta > Estados de Cuenta > Importar Estado de Cuenta",
                "points": [
                    "Descarga el estado de cuenta en formato CSV desde la banca en línea e impórtalo en la cuenta correspondiente.",
                    "Durante la conciliación verás dos paneles: uno con los movimientos del banco y otro con los movimientos registrados en el sistema.",
                    "Selecciona las operaciones relacionadas y empáralas para confirmar que representan el mismo movimiento.",
                    "Si aparece un cargo bancario todavía no registrado, crea la transacción directamente desde la conciliación.",
                    "Cuando corresponda, el sistema crea el movimiento y lo concilia en el mismo flujo.",
                    "Este proceso ayuda a localizar diferencias, movimientos omitidos y cargos bancarios no registrados.",
                ],
                "tip": "Concilia con una frecuencia definida para detectar diferencias cuando todavía son fáciles de investigar.",
            },
            {
                "short_title": "Saldos",
                "title": "4. Revisa y valida los saldos bancarios",
                "intro": "Majjun ERP reúne cobros, pagos y transacciones contabilizadas para mostrar cuánto dinero está disponible en cada cuenta.",
                "route": "Finanzas > Bancos",
                "points": [
                    "Consulta el saldo actual calculado desde la lista de bancos.",
                    "El cálculo considera todos los cobros, pagos y movimientos directos que ya fueron contabilizados.",
                    "Desde el detalle del banco, usa Recalcular saldo cuando detectes una diferencia o quieras validar la información.",
                    "Al recalcular, el sistema vuelve a sumar los movimientos registrados para confirmar que el saldo sea correcto.",
                ],
                "tip": "Si el saldo no coincide con el banco, recalcula y revisa las operaciones pendientes de conciliación.",
            },
        ],
        "cta_title": "Mantén tus saldos bancarios alineados con tu contabilidad",
        "cta_description": "Controla depósitos, retiros, comisiones e intereses desde un mismo flujo y concilia tus estados de cuenta sin perder trazabilidad.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "accounts_receivable": {
        "id": "accounts-receivable",
        "eyebrow": "Gestión de cobranza",
        "title": "Guía de Cuentas por Cobrar en Majjun ERP",
        "description": "Controla quién debe dinero a tu empresa, registra pagos de clientes, da seguimiento a facturas pendientes y organiza la información fiscal relacionada con CFDI.",
        "sections": [
            {
                "short_title": "Facturas",
                "title": "1. Monitorea facturas y vencimientos",
                "intro": "Antes de iniciar la cobranza, identifica qué facturas están pendientes, cuáles ya fueron timbradas y cuáles necesitan atención.",
                "routes": [
                    "Ventas > Facturas",
                    "Cuentas por Cobrar > Reporte de Antigüedad",
                ],
                "points": [
                    "Consulta la columna Estado CFDI para saber si cada factura está timbrada, pendiente o presenta un error.",
                    "Revisa el panel Pendientes de Timbrar para localizar documentos que todavía deben enviarse al SAT.",
                    "Usa el Reporte de Antigüedad para identificar clientes con facturas vencidas.",
                    "Analiza los saldos por rangos de atraso, como 1 a 30 días, 31 a 60 días o más de 60 días.",
                    "Prioriza las facturas con mayor antigüedad o impacto sobre el flujo de efectivo.",
                ],
                "tip": "Revisa diariamente los documentos pendientes de timbrar y define una rutina semanal de seguimiento a vencidos.",
            },
            {
                "short_title": "Pagos",
                "title": "2. Registra pagos según la forma de cobro",
                "intro": "Elige el registro adecuado según si el cliente liquida una factura específica, abona parcialmente o paga varias facturas al mismo tiempo.",
                "routes": [
                    "Ventas > Facturas > Registrar Pago",
                    "Ventas > Recibos de Caja",
                ],
                "points": [
                    "Pago rápido: úsalo cuando el cliente paga una factura específica desde la acción Registrar Pago.",
                    "Confirma el monto pendiente y captura fecha, método de pago y una referencia, como el folio de transferencia.",
                    "Puedes seleccionar transferencia, efectivo u otro método configurado; al registrar, se actualiza el saldo y la factura puede quedar pagada.",
                    "Recibo de caja: úsalo cuando un pago cubre varias facturas, representa un abono o corresponde a un anticipo.",
                    "Crea el recibo, selecciona al cliente, captura el monto total y elige las facturas en Aplicar a Facturas.",
                    "Si queda dinero sin aplicar, puede conservarse como saldo a favor o crédito del cliente.",
                ],
                "tip": "Relaciona cada pago con una referencia clara para facilitar aclaraciones y conciliaciones posteriores.",
            },
            {
                "short_title": "Complemento CFDI",
                "title": "3. Prepara la información fiscal del pago",
                "intro": "Para operaciones en México, el recibo de caja permite organizar los datos necesarios para preparar el complemento de pago cuando corresponda.",
                "route": "Ventas > Recibos de Caja > CFDI",
                "points": [
                    "Abre la pestaña CFDI dentro del recibo de caja.",
                    "Selecciona la Forma de Pago SAT correspondiente, por ejemplo 03 - Transferencia.",
                    "Revisa la moneda y el tipo de cambio detectados por el sistema.",
                    "Al guardar, Majjun ERP prepara la información disponible para continuar con el timbrado fiscal del pago.",
                    "Verifica los datos fiscales antes de avanzar, especialmente cuando existen pagos parciales o monedas distintas.",
                ],
                "tip": "Confirma con tu equipo fiscal cuándo corresponde emitir el complemento y revisa los datos antes de timbrar.",
            },
            {
                "short_title": "Análisis",
                "title": "4. Analiza la cobranza y prioriza el seguimiento",
                "intro": "Los reportes de cobranza muestran cuánto dinero sigue pendiente y cómo evoluciona la cartera para tomar decisiones oportunas.",
                "route": "Cuentas por Cobrar > Reporte de Antigüedad",
                "points": [
                    "Filtra el Reporte de Antigüedad de CxC por fecha de corte para consultar cuánto se debía en un momento específico.",
                    "Exporta o imprime el reporte en PDF cuando necesites compartirlo o utilizarlo como estado de cuenta para un cliente.",
                    "Consulta los totales de la lista de cobranza o recibos de caja para conocer cuánto se ha cobrado hoy.",
                    "Ajusta el rango de fechas para analizar pagos recibidos durante un período determinado.",
                    "Usa la antigüedad y los totales para priorizar llamadas de cobranza y proteger el flujo de efectivo.",
                ],
                "tip": "Da seguimiento primero a saldos vencidos de mayor monto y documenta cada compromiso de pago.",
            },
        ],
        "cta_eyebrow": "Cobranza bajo control",
        "cta_title": "Convierte facturas pendientes en dinero recibido",
        "cta_description": "Identifica facturas vencidas, registra pagos con claridad y mantén tus CFDI y complementos de pago en orden.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "cfdi_guide": {
        "id": "cfdi-guide",
        "eyebrow": "Cumplimiento fiscal",
        "title": "Guía de CFDI 4.0 en Majjun ERP",
        "description": "Emite y administra facturas, notas de crédito y complementos de pago CFDI 4.0 desde Majjun ERP, manteniendo la información fiscal organizada y reduciendo procesos externos.",
        "sections": [
            {
                "short_title": "Configuración",
                "title": "1. Prepara la configuración fiscal",
                "intro": "Antes de emitir comprobantes, registra cuidadosamente la información fiscal de la empresa y las credenciales necesarias para gestionar el timbrado.",
                "route": "Configuración > Configuración CFDI",
                "points": [
                    "Captura el RFC, régimen fiscal y nombre fiscal exactamente como aparecen en la Constancia de Situación Fiscal.",
                    "Carga el certificado CSD con su archivo .cer, llave privada .key y contraseña correspondiente.",
                    "Registra las credenciales del proveedor autorizado de certificación o PAC.",
                    "La conexión con el PAC permite enviar los documentos preparados para su timbrado.",
                    "Esta configuración normalmente se realiza una sola vez, pero debe revisarse cuando cambien certificados o datos fiscales.",
                ],
                "tip": "Verifica cada dato y conserva control sobre la vigencia de los certificados antes de comenzar a timbrar.",
            },
            {
                "short_title": "Catálogos",
                "title": "2. Completa los catálogos fiscales",
                "intro": "Clientes, artículos e impuestos necesitan información fiscal consistente para preparar XML con el desglose adecuado.",
                "points": [
                    "En la pestaña CFDI de cada cliente, registra RFC, código postal fiscal y Uso de CFDI, como Gastos en general.",
                    "En cada artículo, asigna la Clave de Producto o Servicio y la Clave de Unidad correspondiente.",
                    "Para artículos vendidos por pieza, por ejemplo, puede utilizarse la clave de unidad H87 cuando corresponda.",
                    "Configura los códigos de impuestos con su tipo fiscal para representar IVA, ISR, IEPS u otras tasas aplicables.",
                    "Revisa estos datos antes de facturar para reducir rechazos y correcciones posteriores.",
                ],
                "tip": "Mantén los datos fiscales actualizados y valida las claves aplicables con tu equipo contable.",
            },
            {
                "short_title": "Timbrado",
                "title": "3. Convierte documentos listos en CFDI timbrados",
                "intro": "Cuando un documento está preparado o contabilizado, puedes revisar sus datos fiscales y enviarlo al proveedor de timbrado desde Majjun ERP.",
                "route": "Documento listo > CFDI > Timbrar CFDI",
                "points": [
                    "El proceso puede aplicarse a facturas, pagos, notas de crédito o gastos, según las funciones disponibles para cada documento.",
                    "Abre la pestaña CFDI y confirma que el documento esté listo o contabilizado antes de continuar.",
                    "Revisa el Método de Pago: PUE para una sola exhibición o PPD para parcialidades o pago diferido.",
                    "Confirma la Forma de Pago y el resto de la información fiscal.",
                    "Al seleccionar Timbrar CFDI, el sistema envía la información al proveedor de timbrado.",
                    "Si el proceso concluye correctamente, se genera el UUID o Folio Fiscal y quedan disponibles el XML y PDF oficiales cuando corresponda.",
                    "Si ocurre un error, revisa el mensaje mostrado, corrige los datos fiscales y vuelve a intentar.",
                ],
                "tip": "Comprueba cliente, conceptos, impuestos y condiciones de pago antes de enviar el documento a timbrar.",
            },
            {
                "short_title": "Cancelación",
                "title": "4. Solicita la cancelación de comprobantes",
                "intro": "Cuando un CFDI timbrado contiene un error, puedes preparar su solicitud de cancelación y conservar la trazabilidad del cambio.",
                "route": "Documento timbrado > CFDI > Cancelar CFDI",
                "points": [
                    "Abre el comprobante timbrado y selecciona la acción Cancelar CFDI.",
                    "Elige el motivo de cancelación aplicable, como 01 - Errores con relación o 02 - Errores sin relación.",
                    "Cuando selecciones el motivo 01, captura el UUID del comprobante que sustituye al documento cancelado.",
                    "Consulta el estado del documento para verificar cuándo la solicitud haya sido procesada o aceptada.",
                    "Conserva la relación entre documentos para facilitar revisiones y aclaraciones.",
                ],
                "tip": "Confirma el motivo y el UUID relacionado antes de enviar la solicitud de cancelación.",
            },
            {
                "short_title": "Monitoreo",
                "title": "5. Consulta y descarga tus comprobantes",
                "intro": "La vista centralizada de CFDI ayuda a revisar folios fiscales y descargar archivos sin abrir cada documento individualmente.",
                "route": "CFDI > Documentos CFDI",
                "points": [
                    "Consulta facturas, pagos, gastos o notas de crédito timbradas, según corresponda.",
                    "Filtra los documentos por fecha, cliente, proveedor o estado.",
                    "Identifica comprobantes con estado Timbrado, Cancelado, Error o Pendiente cuando esté disponible.",
                    "Descarga el XML y PDF directamente desde la lista.",
                    "Usa esta vista para mantener control de folios fiscales y atender documentos con errores o acciones pendientes.",
                ],
                "tip": "Revisa periódicamente los estados y descarga los archivos necesarios para tus controles internos.",
            },
        ],
        "cta_eyebrow": "Comprobantes organizados",
        "cta_title": "Administra tus CFDI 4.0 sin salir de Majjun ERP",
        "cta_description": "Configura, timbra y consulta comprobantes desde un mismo flujo para reducir errores fiscales y mantener tus documentos en orden.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "ai_guide": {
        "id": "ai-guide",
        "eyebrow": "Automatización inteligente",
        "title": "Guía de IA en Majjun ERP",
        "description": "Usa inteligencia artificial para analizar tu negocio, crear registros con mayor rapidez, recibir sugerencias contables y tomar mejores decisiones sin necesitar conocimientos avanzados de finanzas.",
        "sections": [
            {
                "short_title": "Asistente digital",
                "title": "1. Consulta y crea con el Asistente de IA",
                "intro": "El Asistente de IA funciona como un chat conectado con el contexto de tu negocio para responder preguntas y preparar acciones a partir de instrucciones cotidianas.",
                "routes": [
                    "Menú principal > Icono del robot",
                    "Tablero > Cuadro de texto inferior",
                ],
                "points": [
                    "Escribe preguntas o instrucciones en lenguaje natural, como lo harías al explicarle una tarea a otra persona.",
                    "Usa el modo Analista cuando necesites información, comparativas o explicaciones sobre tus datos.",
                    "Puedes preguntar: ¿Cuáles son mis 5 productos más vendidos? o ¿Qué clientes me deben más de $10,000?",
                    "Usa el modo Asistente cuando quieras crear un registro o preparar una acción.",
                    "Puedes indicar: Registra un gasto de $500 de OfficeDepot por papelería o Crea un pedido para Juan Pérez de 5 cajas de producto X.",
                    "Mientras más contexto incluyas, más precisa será la respuesta o el borrador preparado.",
                ],
                "tip": "Para PyMEs: habla con naturalidad e incluye proveedor, cliente, monto, fecha, producto, cantidad o moneda cuando sean relevantes.",
            },
            {
                "short_title": "Sugerencias",
                "title": "2. Reduce errores con sugerencias inteligentes",
                "intro": "La IA ayuda a resolver dudas contables frecuentes y agiliza la captura de gastos e impuestos en los procesos del día a día.",
                "points": [
                    "Describe un gasto, por ejemplo Tinta para impresora, para recibir una sugerencia de cuenta contable como Gastos de Oficina.",
                    "Cuando aplique, revisa el nivel de confianza de la sugerencia antes de utilizarla.",
                    "Al crear una compra o venta, busca el icono de estrella junto al campo de impuestos.",
                    "La IA analiza el producto, cliente o proveedor para sugerir IVA, retención u otra tasa aplicable.",
                    "Cada sugerencia puede revisarse y ajustarse antes de guardar; el usuario conserva el control de la operación.",
                ],
                "tip": "Confirma la cuenta contable y el tratamiento fiscal antes de guardar registros definitivos.",
            },
            {
                "short_title": "Inventario",
                "title": "3. Optimiza la reposición de inventario",
                "intro": "Las recomendaciones inteligentes ayudan a decidir qué comprar y cuánto pedir con base en existencias e información histórica.",
                "route": "Inventario > Recomendaciones de Reorden > Optimizar con IA",
                "points": [
                    "Consulta productos que se encuentran por debajo de su stock de seguridad.",
                    "La IA analiza ventas anteriores, temporadas y tendencias para preparar cantidades sugeridas.",
                    "Por ejemplo, puede recomendar unidades adicionales cuando un producto suele vender más durante una temporada específica.",
                    "Acepta una recomendación para crear una orden de compra en borrador y revisarla antes de enviarla.",
                    "Este análisis ayuda a evitar faltantes y compras innecesarias.",
                ],
                "tip": "Considera tiempos de entrega y eventos futuros antes de confirmar una recomendación.",
            },
            {
                "short_title": "Tablero",
                "title": "4. Analiza el negocio desde el tablero",
                "intro": "El tablero combina información visual y accesos rápidos para convertir datos recientes en decisiones más ágiles.",
                "route": "Tablero principal",
                "points": [
                    "Consulta KPIs con comparativas frente al mes anterior y tendencias recientes.",
                    "Los gráficos compactos ayudan a reconocer cambios sin abrir reportes adicionales.",
                    "Usa los prompts rápidos o botones con preguntas sugeridas para iniciar un análisis.",
                    "Selecciona una consulta como Ventas totales este mes para obtener información sin navegar por varios menús.",
                    "Apóyate en el contexto de los indicadores para decidir qué necesita atención.",
                ],
                "tip": "Revisa primero los cambios más relevantes y pide a la IA que explique cualquier variación inesperada.",
            },
            {
                "short_title": "Seguimiento",
                "title": "5. Revisa las acciones preparadas por la IA",
                "intro": "Cuando la IA crea o prepara un registro, puedes consultar su progreso y verificar el resultado antes de continuar con otros procesos.",
                "route": "Panel de Acciones Recientes",
                "points": [
                    "Consulta cada acción con estado Pendiente, Ejecutada o Error.",
                    "Revisa las acciones pendientes para confirmar si todavía requieren aprobación o información adicional.",
                    "Abre las acciones con error para identificar qué dato necesita corrección.",
                    "Verifica qué hizo la IA y conserva el control sobre registros, gastos, facturas y movimientos preparados con su ayuda.",
                ],
                "tip": "Revisa periódicamente las acciones recientes para atender errores y confirmar que cada resultado sea correcto.",
            },
        ],
        "cta_eyebrow": "IA con control humano",
        "cta_title": "Convierte tus datos en decisiones más claras",
        "cta_description": "Analiza, crea y revisa información con apoyo de IA para ahorrar tiempo en tareas operativas sin perder control.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "segments": {
        "id": "segments",
        "eyebrow": "Casos de uso",
        "title": "Majjun ERP para cada etapa y tipo de negocio.",
        "description": "La misma base tecnologica, con flujos adaptados al ritmo y necesidad de cada equipo.",
        "segment_intro": "Elige el recorrido que se parece a tu operacion y escala por modulos.",
        "items": [
            {
                "eyebrow": "Gestion de ventas",
                "title": "Ventas y Clientes",
                "description": "Gestiona clientes, registra pedidos, controla entregas, emite facturas y convierte cada venta en dinero recibido desde un flujo conectado.",
                "flow": [
                    "Cliente",
                    "Pedido",
                    "Almacén",
                    "Factura",
                    "Cobranza",
                ],
                "cta_href": "/comercial/ventas-y-clientes/",
            },
            {
                "eyebrow": "Servicios recurrentes",
                "title": "Contratos de Retainer",
                "description": "Gestiona compromisos continuos con clientes, asegura ingresos predecibles, audita horas con apoyo de IA y convierte servicios aprobados en facturas cobrables.",
                "flow": [
                    "Crear",
                    "Activar",
                    "Horas",
                    "Aprobar",
                    "Facturar",
                    "Renovar",
                ],
                "cta_href": "/comercial/contratos-de-retainer/",
            },
        ],
    },
    "sales_customers": {
        "id": "sales-customers",
        "eyebrow": "Gestion de ventas",
        "title": "Ventas y Clientes en Majjun ERP",
        "description": "Gestiona clientes, registra pedidos, controla entregas, emite facturas y convierte cada venta en dinero recibido desde un flujo conectado.",
        "flow": [
            "Cliente",
            "Pedido",
            "Almacen",
            "Factura",
            "Cobranza",
            "Devolucion",
        ],
        "sections": [
            {
                "short_title": "Clientes",
                "title": "1. Organiza tu base de clientes",
                "intro": "El primer paso para vender con orden es contar con informacion confiable de cada cliente. Una base bien organizada agiliza cotizaciones, pedidos y facturas.",
                "route": "Ventas > Clientes",
                "points": [
                    "Crea un nuevo cliente y registra el nombre de la empresa o persona, email y RFC o ID fiscal.",
                    "Define los terminos de pago, por ejemplo 30 dias de credito, y selecciona la moneda de cobro.",
                    "Guarda direcciones de facturacion y envio por separado cuando la operacion lo requiera.",
                    "Establece un limite de credito para controlar cuanto puede deber el cliente antes de solicitar un pago.",
                ],
                "tip": "Mantener los datos fiscales y de entrega actualizados evita correcciones al momento de facturar o enviar.",
            },
            {
                "short_title": "Pedidos",
                "title": "2. Confirma pedidos con inventario disponible",
                "intro": "Los pedidos registran lo que solicita cada cliente y ayudan a comprometer existencias antes de preparar la entrega.",
                "route": "Ventas > Pedidos",
                "points": [
                    "Crea un nuevo pedido y selecciona al cliente para completar sus datos de envio y terminos de pago.",
                    "Agrega los productos solicitados y revisa el stock disponible para evitar sobreventas.",
                    "Confirma cantidades, precios y fechas antes de aprobar el pedido.",
                    "Al confirmar, el inventario queda asignado o reservado para ese cliente.",
                ],
                "tip": "Revisa la disponibilidad antes de prometer una fecha de entrega.",
            },
            {
                "short_title": "Almacen",
                "title": "3. Prepara cada salida desde el almacen correcto",
                "intro": "Indicar el origen exacto de cada producto mantiene el inventario preciso y permite que el equipo prepare entregas sin confusiones.",
                "points": [
                    "Desde un pedido de venta o factura, abre las partidas para revisar los articulos.",
                    "Selecciona el almacen de salida, por ejemplo Sucursal Norte.",
                    "Indica la ubicacion correspondiente, como Pasillo 2.",
                    "Comprueba el stock disponible en esa ubicacion antes de confirmar la salida.",
                ],
                "tip": "Elegir almacen y ubicacion en cada partida mejora la trazabilidad de la entrega.",
            },
            {
                "short_title": "Facturacion",
                "title": "4. Convierte pedidos en facturas oficiales",
                "intro": "Un pedido confirmado puede convertirse en factura para formalizar la venta y dar seguimiento tanto al cobro como al estado fiscal.",
                "route": "Ventas > Facturas",
                "points": [
                    "Convierte el pedido confirmado en factura y revisa los datos antes de publicarla.",
                    "Al publicar, el sistema genera el numero oficial del documento y actualiza cuentas por cobrar.",
                    "Consulta el semaforo CFDI para identificar documentos con estado Timbrada, Pendiente o Error.",
                    "Usa el panel Pendientes de Timbrar para localizar facturas que aun deben enviarse al SAT.",
                ],
                "tip": "Atiende los documentos pendientes o con error para mantener la operacion fiscal al dia.",
            },
            {
                "short_title": "Cobranza",
                "title": "5. Registra cobros sin pasos contables complejos",
                "intro": "Registrar un pago debe ser rapido y claro para que el saldo de cada cliente refleje la realidad.",
                "points": [
                    "Desde la lista de facturas, selecciona la opcion para registrar un pago.",
                    "El sistema toma el saldo pendiente; confirma el monto y la fecha recibida.",
                    "Selecciona el metodo de pago, como transferencia, cheque u otro metodo configurado.",
                    "Al registrar el pago, se actualizan el saldo de la factura y los estados financieros.",
                ],
                "tip": "Registra cada cobro al recibirlo para conservar una cartera confiable.",
            },
            {
                "short_title": "Devoluciones",
                "title": "6. Gestiona devoluciones y notas de credito",
                "intro": "Cuando un cliente regresa mercancia, el sistema ayuda a ajustar cuentas, inventario e impuestos sin perder el historial de la venta.",
                "route": "Ventas > Devoluciones",
                "points": [
                    "Crea una nueva devolucion y selecciona la factura para consultar los articulos vendidos originalmente.",
                    "Indica la razon, por ejemplo Danado, y registra la cantidad recibida.",
                    "Confirma si el producto debe regresar al inventario.",
                    "Al publicar, se genera la nota de credito, se ajusta la deuda del cliente y se actualizan los impuestos correspondientes.",
                ],
                "tip": "Documenta la razon de cada devolucion para detectar problemas recurrentes.",
            },
        ],
        "cta_title": "Gestiona tus ventas de principio a fin",
        "cta_description": "Controla clientes, inventario, CFDI y cobranza desde un solo flujo.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "retainer_contracts": {
        "id": "retainer-contracts",
        "eyebrow": "Servicios recurrentes",
        "title": "Guía de Contratos de Retainer en Majjun ERP",
        "description": "Gestiona compromisos continuos con clientes, asegura ingresos predecibles, audita horas con apoyo de IA y convierte servicios aprobados en facturas cobrables.",
        "flow": [
            "Crear contrato",
            "Definir servicios",
            "Activar",
            "Registrar horas",
            "Aprobar",
            "Facturar",
            "Renovar",
            "Cerrar",
            "Monitorear",
        ],
        "sections": [
            {
                "short_title": "Creación",
                "title": "1. Registra el acuerdo y prepara los cobros",
                "intro": "El primer paso es capturar las condiciones del servicio recurrente para automatizar el seguimiento y construir un calendario de cobro confiable.",
                "route": "Órdenes de Servicio > Contratos de Retainer",
                "points": [
                    "Crea un nuevo contrato y asigna un nombre descriptivo, cliente, fecha de inicio y fecha de vencimiento.",
                    "Define la periodicidad de cobro, ya sea mensual, trimestral u otra, junto con la moneda acordada.",
                    "Configura las horas laborables por día y los días previos al cierre para que la IA pueda sugerir cuándo facturar.",
                    "Al guardar, el contrato queda en borrador y recibe un folio con formato RET-AAAA-NNNN.",
                    "Adjunta el SOW o el contrato firmado en PDF para conservar toda la evidencia junto al acuerdo.",
                ],
                "tip": "Verifica fechas, moneda y periodicidad antes de continuar; estos datos determinan el calendario de facturación.",
            },
            {
                "short_title": "Servicios",
                "title": "2. Define los servicios y asigna al equipo",
                "intro": "Antes de activar el contrato, especifica qué incluye el acuerdo y quién puede trabajar en cada servicio.",
                "route": "Contrato en borrador > Servicios > Agregar Servicio",
                "points": [
                    "Selecciona el tipo de servicio y define si se cobrará con tarifa fija o por hora.",
                    "Asigna a los empleados responsables de cada línea de servicio.",
                    "El costo interno de cada empleado permite calcular la rentabilidad esperada y real.",
                    "Un empleado no puede asignarse dos veces a la misma línea de servicio.",
                    "Solo el personal asignado puede registrar horas en ese contrato.",
                ],
                "tip": "Revisa las asignaciones y tarifas antes de activar para medir correctamente costos y margen.",
            },
            {
                "short_title": "Activación",
                "title": "3. Activa el contrato y registra el trabajo",
                "intro": "La activación pone en marcha el acuerdo, genera sus períodos de cobro y habilita el registro de tiempos para el equipo asignado.",
                "points": [
                    "Activa el contrato desde el encabezado para generar automáticamente el calendario de facturación.",
                    "Los empleados asignados pueden registrar fecha, número de horas y una descripción del trabajo realizado.",
                    "Cada fecha debe estar dentro de la vigencia del contrato y del período activo.",
                    "Al guardar, el registro queda pendiente de revisión antes de afectar los acumulados reales.",
                ],
                "tip": "Solicita descripciones concretas para que la revisión y la conciliación sean más rápidas.",
            },
            {
                "short_title": "Aprobaciones",
                "title": "4. Revisa y aprueba los tiempos",
                "intro": "Un gerente o supervisor valida el trabajo registrado antes de que las horas y costos impacten el contrato.",
                "points": [
                    "Consulta los registros pendientes y confirma que las fechas, horas y descripciones sean correctas.",
                    "Al aprobar, las horas y sus costos se suman al acumulado real del contrato.",
                    "Rechaza los registros con errores para que el empleado pueda corregirlos o eliminarlos.",
                ],
                "tip": "Audita el trabajo del equipo antes de facturar para evitar ajustes posteriores.",
            },
            {
                "short_title": "Facturación",
                "title": "5. Convierte horas aprobadas en facturas",
                "intro": "La conciliación reúne la evidencia operativa del período y ayuda a transformar el trabajo aprobado en un cobro listo para revisar.",
                "route": "Contrato > Calendario de Facturación",
                "points": [
                    "Ejecuta la conciliación para comparar las horas estimadas contra las horas reales.",
                    "Factura el período actual para crear un borrador de factura en Finanzas.",
                    "Las horas aprobadas asociadas quedan bloqueadas y ya no pueden modificarse.",
                    "La IA puede identificar períodos listos para facturar y señalar posibles inconsistencias.",
                ],
                "tip": "Concilia estimaciones, horas reales y tarifas antes de generar el borrador de factura.",
            },
            {
                "short_title": "Renovaciones",
                "title": "6. Renueva sin reconstruir el contrato",
                "intro": "Cuando un acuerdo activo se acerca a su vencimiento, puedes preparar el siguiente ciclo conservando su historial y trazabilidad.",
                "points": [
                    "Inicia la renovación desde el contrato activo próximo a vencer; el sistema propone las nuevas fechas.",
                    "Ajusta precios o tarifas para el siguiente ciclo cuando sea necesario.",
                    "El contrato anterior cambia a estado renovado y conserva su historial.",
                    "Se crea un nuevo contrato en borrador relacionado con el original para mantener la trazabilidad.",
                ],
                "tip": "Revisa alcance, capacidad del equipo y rentabilidad antes de confirmar nuevas tarifas.",
            },
            {
                "short_title": "Cancelaciones",
                "title": "7. Termina contratos de forma ordenada",
                "intro": "El cierre controlado protege el historial del acuerdo y evita que se generen nuevos servicios o tiempos después de la fecha efectiva.",
                "points": [
                    "Selecciona Terminar contrato desde el encabezado e indica una categoría: solicitud del cliente, impago, cambio de alcance u otra.",
                    "Captura un motivo obligatorio y define la fecha efectiva de terminación.",
                    "Una fecha de hoy o pasada cancela de inmediato; una fecha futura deja el contrato en terminación pendiente.",
                    "Al cancelar, se anulan los períodos futuros pendientes, pero las facturas emitidas no se alteran.",
                    "Cualquier devolución requiere una nota de crédito manual.",
                    "Los contratos cancelados quedan bloqueados contra nuevos servicios, asignaciones y registros de tiempo.",
                ],
                "tip": "Documenta el motivo con claridad para conservar un historial útil en futuras negociaciones.",
            },
            {
                "short_title": "Tablero",
                "title": "8. Anticipa vencimientos desde el tablero",
                "intro": "El panel de contratos por vencer concentra las acciones necesarias para no perder renovaciones ni ingresos recurrentes.",
                "points": [
                    "El semáforo rojo identifica contratos que vencen en 7 días o menos.",
                    "El semáforo naranja muestra contratos que vencen entre 8 y 30 días.",
                    "Usa las acciones rápidas para abrir el contrato, renovarlo o facturar el próximo período pendiente.",
                ],
                "tip": "Revisa este panel cada semana para preparar renovaciones y cobros antes del vencimiento.",
            },
        ],
        "rules": [
            ("BR-RA-01", "General", "El nombre del contrato es obligatorio."),
            ("BR-RA-02", "General", "La fecha de inicio debe ser menor o igual que la fecha de vencimiento."),
            ("BR-RA-03", "General", "El límite diario por defecto es 8 horas si no se configura otro valor."),
            ("BR-RA-04", "General", "La ventana sugerida para facturación con IA es de 5 días antes del período."),
            ("BR-RA-05", "Servicios", "La tarifa fija es obligatoria cuando el método es tarifa fija."),
            ("BR-RA-06", "Servicios", "Tarifas y horas estimadas deben ser valores no negativos."),
            ("BR-RA-07", "Asignación", "El personal asignado debe estar activo."),
            ("BR-RA-08", "Asignación", "Se bloquea la doble asignación de un empleado a la misma línea."),
            ("BR-RA-09", "Asignación", "El costo estimado usa la tarifa interna del empleado si está asignado; si no, usa la tarifa del servicio."),
            ("BR-RA-10", "Tiempos", "Los empleados solo registran horas en líneas asignadas."),
            ("BR-RA-11", "Tiempos", "Las fechas deben caer dentro de la vigencia y del período activo."),
            ("BR-RA-12", "Tiempos", "Los registros deben tener una duración mayor a cero."),
            ("BR-RA-13", "Tiempos", "Un registro facturado queda bloqueado."),
            ("BR-RA-14", "Facturación", "Se aplica prorrateo diario para períodos parciales."),
            ("BR-RA-15", "Facturación", "Los períodos facturados bloquean las horas aprobadas asociadas."),
            ("BR-RA-29", "Renovación", "La renovación clona el contrato y marca el original como renovado."),
            ("BR-RA-30", "Renovación", "El nuevo contrato conserva la referencia al contrato original."),
            ("BR-RA-31", "Renovación", "Los ajustes de tarifa quedan en la bitácora de auditoría."),
            ("BR-RA-32", "Cancelación", "La terminación solo aplica a contratos activos o expirados."),
            ("BR-RA-33", "Cancelación", "La categoría y el motivo son obligatorios."),
            ("BR-RA-34", "Cancelación", "Las fechas futuras dejan la terminación pendiente; las presentes o pasadas cancelan."),
            ("BR-RA-35", "Cancelación", "Solo se anulan períodos pendientes posteriores a la fecha efectiva."),
            ("BR-RA-36", "Cancelación", "Los períodos facturados no se alteran y requieren una nota de crédito manual."),
            ("BR-RA-37", "Cancelación", "Las horas pendientes muestran una advertencia, pero no bloquean la cancelación."),
            ("BR-RA-38", "Cancelación", "Los contratos cancelados quedan bloqueados permanentemente."),
            ("BR-RA-39", "Tablero", "Rojo con 7 días o menos; naranja de 8 a 30 días."),
        ],
        "cta_title": "Convierte servicios recurrentes en ingresos predecibles",
        "cta_description": "Controla horas, costos y facturación desde un mismo flujo, y renueva contratos a tiempo.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "accounts_payable": {
        "id": "accounts-payable",
        "eyebrow": "Gestion de egresos",
        "title": "Cuentas por Pagar en Majjun ERP",
        "description": "Registra lo que debes a tus proveedores, organiza gastos, realiza pagos, vincula comprobantes fiscales y conoce tu deuda total con claridad.",
        "flow": [
            "Registrar gasto",
            "Contabilizar",
            "Pagar",
            "Vincular CFDI",
            "Revisar reportes",
        ],
        "sections": [
            {
                "short_title": "Gastos",
                "title": "1. Registra facturas y gastos de proveedores",
                "intro": "Todo comienza al capturar la factura, gasto o costo recibido. Puedes importar el comprobante para ahorrar tiempo o registrar la informacion manualmente.",
                "route": "Cuentas por Pagar > Gastos",
                "groups": [
                    {
                        "label": "Opcion recomendada",
                        "title": "Importacion desde XML",
                        "points": [
                            "Importa el archivo XML para que el sistema lea proveedor, productos e impuestos automaticamente.",
                            "Revisa los datos detectados antes de crear el gasto.",
                            "Guarda el gasto como borrador si todavia necesita validacion antes de contabilizarse.",
                        ],
                    },
                    {
                        "label": "Captura flexible",
                        "title": "Registro manual",
                        "points": [
                            "Crea un nuevo gasto y selecciona el proveedor y la fecha de vencimiento.",
                            "Agrega articulos con descripcion, cantidad y precio.",
                            "Selecciona la cuenta contable o Cuenta GL adecuada, por ejemplo Papeleria o Renta.",
                            "Guarda como borrador o contabiliza cuando la informacion sea definitiva.",
                        ],
                    },
                ],
                "tip": "Importar el XML reduce captura manual; en ambos casos, revisa la cuenta contable antes de contabilizar.",
            },
            {
                "short_title": "Pagos",
                "title": "2. Registra pagos individuales o masivos",
                "intro": "Cuando el gasto esta contabilizado, registra la salida de dinero y manten actualizado el saldo de cada proveedor.",
                "groups": [
                    {
                        "label": "Una factura",
                        "title": "Pago rapido",
                        "points": [
                            "Desde la lista de gastos, selecciona la opcion para registrar el pago.",
                            "Revisa el saldo pendiente y decide si pagaras el total o solo una parte.",
                            "Selecciona cuenta bancaria, metodo de pago y referencia bancaria.",
                            "Usa transferencia, efectivo, cheque u otro metodo configurado; al registrar, el saldo se actualiza.",
                        ],
                    },
                    {
                        "label": "Varias facturas",
                        "title": "Pago masivo",
                        "route": "Compras > Pagos",
                        "points": [
                            "Crea un nuevo pago y selecciona al proveedor para consultar sus gastos pendientes.",
                            "Ingresa el monto total pagado y distribuyelo entre las facturas o gastos.",
                            "Comprueba que el saldo no aplicado sea cero.",
                            "Al contabilizar, el sistema registra el pago y actualiza cada saldo relacionado.",
                        ],
                    },
                ],
                "tip": "Usa pagos masivos cuando una sola transferencia o cheque liquide varios gastos del mismo proveedor.",
            },
            {
                "short_title": "CFDI",
                "title": "3. Mantén tus comprobantes fiscales vinculados",
                "intro": "Relacionar cada gasto y pago con su comprobante correspondiente facilita el cumplimiento fiscal y conserva la trazabilidad.",
                "points": [
                    "Si el gasto no se creo mediante importacion, entra al gasto y sube el XML y PDF de la factura en la pestana CFDI.",
                    "Cuando recibas el complemento de pago, busca el pago contabilizado en la lista de pagos y carga su XML.",
                    "El sistema valida automaticamente que el RFC del comprobante coincida.",
                    "Conserva cada documento junto a la operacion para facilitar revisiones y aclaraciones.",
                ],
                "tip": "Vincula los comprobantes al recibirlos para evitar expedientes fiscales incompletos.",
            },
            {
                "short_title": "Reportes",
                "title": "4. Conoce cuanto debes y prioriza pagos",
                "intro": "Los reportes de Cuentas por Pagar muestran a quien debes, cuanto debes y que compromisos necesitan atencion inmediata.",
                "points": [
                    "Consulta el reporte de Antiguedad de CxP para identificar proveedores con saldos pendientes.",
                    "Revisa los rangos de atraso, por ejemplo de 0 a 15 dias o mas de 30 dias.",
                    "Exporta la informacion a Excel desde la lista de gastos cuando necesites compartirla o analizarla.",
                    "Usa estos datos para priorizar pagos y proteger el flujo de efectivo.",
                ],
                "tip": "Revisa la antiguedad de saldos con frecuencia para anticipar vencimientos y negociar a tiempo.",
            },
        ],
        "cta_title": "Controla tus pagos a proveedores con mayor claridad",
        "cta_description": "Registra gastos, realiza pagos y manten tus CFDI en orden sin perder trazabilidad.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "logistics_warehouses": {
        "id": "logistics-warehouses",
        "eyebrow": "Gestión de almacenes",
        "title": "Guía de Logística y Almacenes en Majjun ERP",
        "description": "Organiza espacios físicos, controla existencias por ubicación, mueve mercancía entre sucursales y usa inteligencia artificial para decidir qué comprar y cuándo hacerlo.",
        "flow": [
            "Almacenes",
            "Ubicaciones",
            "Transferencias",
            "Ensamblajes",
            "Reorden inteligente",
            "Auditoría",
        ],
        "sections": [
            {
                "short_title": "Almacenes",
                "title": "1. Organiza almacenes y ubicaciones",
                "intro": "Conocer la existencia total es importante, pero identificar el lugar exacto donde se encuentra cada artículo permite operar con mayor precisión.",
                "route": "Inventario > Almacenes y Ubicaciones",
                "points": [
                    "Registra almacenes para representar sitios físicos, como Bodega Principal o Sucursal Norte.",
                    "Crea ubicaciones internas para identificar espacios como Pasillo 1, Estante A o Cámara de Frío.",
                    "Al vender o facturar, selecciona el almacén y la ubicación correspondiente en cada partida.",
                    "El sistema descuenta las existencias del lugar seleccionado para reflejar el movimiento real.",
                    "Una estructura clara reduce diferencias de stock y facilita la preparación de pedidos.",
                ],
                "tip": "Usa nombres consistentes para que el equipo pueda localizar mercancía y registrar salidas sin confusiones.",
            },
            {
                "short_title": "Transferencias",
                "title": "2. Mueve mercancía entre almacenes",
                "intro": "Las transferencias registran el traslado de artículos entre sucursales, almacenes o ubicaciones internas sin perder visibilidad de las existencias.",
                "route": "Inventario > Transferencias",
                "points": [
                    "Crea una nueva transferencia y busca artículos por nombre o código.",
                    "Escribe parte del nombre o código para filtrar rápidamente los productos disponibles.",
                    "Selecciona la ubicación de origen y el destino de la mercancía.",
                    "Consulta la disponibilidad en el origen para evitar trasladar más unidades de las existentes.",
                    "Al confirmar, el stock se descuenta del origen y se suma automáticamente al destino.",
                ],
                "tip": "Confirma cantidades, origen y destino antes de completar el movimiento.",
            },
            {
                "short_title": "Kits",
                "title": "3. Ensambla kits y productos compuestos",
                "intro": "Los ensamblajes simplifican la preparación de paquetes, combos y productos compuestos antes de venderlos, conservando el control de sus componentes.",
                "route": "Inventario > Ensamblajes",
                "points": [
                    "Selecciona el kit que deseas preparar e indica la cantidad a producir, por ejemplo 10 unidades.",
                    "Al completar el ensamblaje, el sistema descuenta del inventario los componentes individuales utilizados.",
                    "Los kits terminados se agregan automáticamente a las existencias disponibles.",
                    "Utiliza este flujo para preparar una canasta de regalo, un paquete promocional o un equipo armado.",
                    "Así puedes gestionar producción ligera sin perder precisión en el inventario.",
                ],
                "tip": "Verifica la disponibilidad de todos los componentes antes de iniciar un ensamblaje.",
            },
            {
                "short_title": "Reposición",
                "title": "4. Anticipa la reposición con recomendaciones inteligentes",
                "intro": "Las recomendaciones de reorden ayudan a comprar a tiempo y con mejores cantidades antes de que un producto se convierta en faltante.",
                "route": "Inventario > Recomendaciones de Reorden",
                "points": [
                    "Consulta los productos que se encuentran por debajo de su stock de seguridad.",
                    "La IA analiza ventas anteriores, tendencias y comportamiento de demanda para preparar sugerencias.",
                    "Revisa las cantidades recomendadas para equilibrar disponibilidad, costo y rentabilidad.",
                    "Acepta una sugerencia para generar una orden de compra en borrador y revisarla antes de enviarla.",
                    "Agrupa productos por proveedor para preparar órdenes de compra con mayor rapidez.",
                    "Este proceso ayuda a evitar faltantes y compras innecesarias.",
                ],
                "tip": "Combina las recomendaciones con tiempos de entrega y temporadas antes de confirmar la compra.",
            },
            {
                "short_title": "Auditoría",
                "title": "5. Audita cada movimiento de inventario",
                "intro": "La trazabilidad permite entender por qué cambió la existencia de un producto y facilita la investigación de cualquier diferencia.",
                "route": "Inventario > Lista de Inventario > Detalle del producto",
                "points": [
                    "Abre el detalle de un producto desde la lista de inventario para consultar su historial.",
                    "Revisa movimientos originados por transferencias, ventas, facturas, ajustes manuales o mermas.",
                    "Identifica quién realizó cada movimiento, cuándo ocurrió y qué documento lo generó.",
                    "Usa esta información para investigar diferencias de inventario y fortalecer el control interno.",
                ],
                "tip": "Consulta el historial antes de realizar un ajuste manual para conservar una explicación clara de la diferencia.",
            },
        ],
        "cta_eyebrow": "Logística conectada",
        "cta_title": "Controla tu inventario desde el almacén hasta la venta",
        "cta_description": "Organiza ubicaciones, transferencias y reposición desde un mismo flujo, con trazabilidad completa de cada movimiento.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "purchases_suppliers": {
        "id": "purchases-suppliers",
        "eyebrow": "Gestion de compras",
        "title": "Compras y Proveedores",
        "description": "Administra proveedores, controla solicitudes y ordenes de compra, recibe mercancia con precision y anticipa el reorden con recomendaciones inteligentes.",
        "flow": [
            "Proveedor",
            "Requisicion",
            "Orden de compra",
            "Recepcion",
            "Inventario",
            "Reorden inteligente",
        ],
        "sections": [
            {
                "short_title": "Proveedores",
                "title": "1. Organiza tu catalogo de proveedores",
                "intro": "Antes de generar una orden de compra, registra los datos comerciales y financieros de cada proveedor para agilizar futuras operaciones.",
                "route": "Compras > Proveedores",
                "points": [
                    "Crea un nuevo proveedor y registra su nombre, RFC o ID fiscal y contacto principal.",
                    "Define los terminos de pago habituales, como contado o 30 dias.",
                    "Selecciona la moneda que el proveedor utiliza normalmente para facturar.",
                    "Al guardar, el sistema reutiliza estos datos automaticamente en futuras compras.",
                ],
                "tip": "Mantén actualizados los datos fiscales, contactos y condiciones negociadas para evitar correcciones posteriores.",
            },
            {
                "short_title": "Requisiciones",
                "title": "2. Convierte solicitudes internas en compras aprobadas",
                "intro": "Las requisiciones permiten que un empleado solicite articulos y que otra persona autorice la compra antes de comprometer presupuesto.",
                "route": "Compras > Requisiciones de Compra",
                "points": [
                    "Crea una nueva requisicion y selecciona los articulos necesarios.",
                    "Indica la fecha requerida para que el equipo de compras pueda planear.",
                    "Guarda y envia la solicitud para que quede pendiente de aprobacion.",
                    "Una persona con permisos puede aprobarla y convertirla en orden de compra sin capturar la informacion dos veces.",
                ],
                "tip": "Usa requisiciones para conservar evidencia de quien solicito, reviso y aprobo cada compra.",
            },
            {
                "short_title": "Ordenes",
                "title": "3. Formaliza cada solicitud con una orden de compra",
                "intro": "La orden de compra comunica al proveedor que productos o servicios necesitas, bajo que condiciones y donde esperas recibirlos.",
                "route": "Compras > Ordenes de Compra",
                "points": [
                    "Crea una nueva orden y selecciona rapidamente articulos escribiendo parte de su nombre o codigo.",
                    "Revisa los impuestos calculados por articulo; la IA puede sugerir la tasa adecuada.",
                    "Indica el almacen o ubicacion donde esperas recibir cada producto.",
                    "Al enviar la orden, su estado cambia a Enviado y queda lista para seguimiento.",
                ],
                "tip": "Confirma cantidades, impuestos, fechas y ubicacion esperada antes de enviar la orden al proveedor.",
            },
            {
                "short_title": "Recepcion",
                "title": "4. Registra exactamente lo que recibes",
                "intro": "La recepcion de bienes registra la entrada real de mercancia y mantiene sincronizados el inventario y la orden de compra.",
                "route": "Compras > Recepcion de Bienes",
                "points": [
                    "Crea una nueva recepcion y selecciona la orden de compra correspondiente.",
                    "Consulta lo pedido y lo que todavia esta pendiente por recibir.",
                    "Captura la cantidad realmente recibida; si algo llego danado o incompleto, registra una cantidad menor.",
                    "Mientras la recepcion permanezca en borrador, el inventario no cambia.",
                    "Al publicar, aumentan las existencias y la orden se actualiza como recibida total o parcialmente.",
                ],
                "tip": "Cuenta y revisa la mercancia antes de publicar para que las existencias reflejen la recepcion real.",
            },
            {
                "short_title": "Reorden con IA",
                "title": "5. Anticipa compras con recomendaciones inteligentes",
                "intro": "Las recomendaciones de reorden ayudan a identificar que productos necesitan reposicion antes de que se conviertan en faltantes.",
                "route": "Inventario > Recomendaciones de Reorden",
                "points": [
                    "Consulta los productos que requieren reposicion segun sus niveles minimos de stock.",
                    "La optimizacion con IA analiza ventas anteriores, temporadas y patrones de demanda.",
                    "Antes de una temporada alta, el sistema puede sugerir comprar mas unidades de un producto con mayor demanda esperada.",
                    "Acepta una recomendacion para crear una orden de compra en borrador y revisarla antes de enviarla.",
                ],
                "tip": "Combina las recomendaciones con tiempos de entrega y condiciones del proveedor antes de confirmar la compra.",
            },
        ],
        "cta_title": "Compra con mas control y menos captura manual",
        "cta_description": "Administra proveedores, ordenes y recepciones desde un mismo flujo y evita faltantes con recomendaciones inteligentes.",
        "cta_label": "Conocer Majjun ERP",
        "cta_href": "/soporte/",
    },
    "inventarios": {
        "id": "inventarios",
        "module_title": "Modulo de Inventarios",
        "module_intro": "Administra tus productos, controla tus existencias en tiempo real y gestiona tus kits de venta de forma profesional.",
        "module_sections": [
            {
                "title": "1. Tu Catalogo de Productos",
                "route": "Inventario > Articulos",
                "points": [
                    "Antes de vender o comprar, define tus productos o servicios en Inventario > Articulos.",
                    "Haz clic en + Nuevo Articulo y selecciona el tipo: Inventario para fisicos o Servicio para intangibles.",
                    "Asigna Codigo unico, Nombre y Precio de Lista para cada articulo.",
                    "Configura Stock Minimo para recibir alertas de recompra.",
                ],
                "tip": "Usa codigos unicos y consistentes desde el inicio para facilitar busquedas y reportes a futuro.",
            },
            {
                "title": "2. Kits y Recetas",
                "route": "Inventario > Articulos > Pestana BOM",
                "points": [
                    "Crea un articulo de tipo Kit o Receta cuando vendas paquetes o productos compuestos.",
                    "En la pestana BOM, agrega componentes y cantidades con Anadir Componente.",
                    "Usa Aplicar Precios para calcular costo total y sugerir precio de venta por margen.",
                ],
                "tip": "Revisa la disponibilidad de todos los componentes antes de crear un kit o iniciar un ensamblaje.",
            },
            {
                "title": "3. Control de Existencias",
                "route": "Inventario > Lista de Inventario",
                "points": [
                    "Consulta Inventario > Lista de Inventario para revisar En Mano, Reservado y Disponible.",
                    "En Mano: stock fisico actual.",
                    "Reservado: vendido pero no entregado.",
                    "Disponible: libre para nuevas ventas.",
                    "Si hay diferencias, abre el historial con el icono del ojo para ver entradas, salidas, ajustes y usuario responsable.",
                ],
                "metrics": [
                    {"label": "En Mano",    "desc": "Stock fisico actual en tu bodega."},
                    {"label": "Reservado",  "desc": "Vendido pero aun no entregado."},
                    {"label": "Disponible", "desc": "Libre para nuevas ventas."},
                ],
                "tip": "Si un numero no te cuadra, abre el historial con el icono del ojo para ver cada movimiento y el usuario que lo realizo.",
            },
            {
                "title": "4. Ajustes y Transferencias",
                "route": "Inventario > Transferencias",
                "points": [
                    "Para dano, merma o sobrante, haz ajuste manual desde el icono de Caja con cantidad positiva o negativa.",
                    "Para mover stock entre ubicaciones, usa Inventario > Transferencias.",
                    "La barra de busqueda filtra por nombre o codigo al escribir 3 caracteres.",
                ],
                "tip": "La barra de busqueda filtra articulos al escribir 3 caracteres; usala para localizar productos antes de ajustar.",
            },
            {
                "title": "5. Armado de Productos",
                "route": "Inventario > Ensamblajes",
                "points": [
                    "Si pre-ensamblas kits, entra a Inventario > Ensamblajes y selecciona Crear Ensamblaje.",
                    "Indica Kit y Cantidad a armar.",
                    "Al Completar Ensamblaje, el sistema resta componentes y suma kits terminados listos para venta.",
                ],
                "tip": "Verifica la disponibilidad de todos los componentes antes de iniciar un ensamblaje para evitar interrupciones.",
            },
        ],
        "faq": [
            {
                "q": "¿Cual es la diferencia entre un articulo de Inventario y uno de Servicio?",
                "a": "Un articulo de Inventario es un producto fisico que ocupa espacio en tu bodega y se descuenta del stock al venderse. Un Servicio es mano de obra o un intangible, como una instalacion, que no afecta el stock fisico.",
            },
            {
                "q": "¿Como calcula el sistema el precio de un kit?",
                "a": "Al usar el boton Aplicar Precios en la pestana BOM, el sistema suma el costo de todos los componentes y sugiere un precio de venta segun el margen de ganancia que definas.",
            },
            {
                "q": "¿Que significa que un articulo este Reservado?",
                "a": "Reservado es la cantidad que ya vendiste pero aun no has entregado al cliente. No esta disponible para nuevas ventas, pero sigue fisicamente en tu bodega hasta que se entregue.",
            },
            {
                "q": "¿Puedo corregir el stock si encuentro mercancia danada?",
                "a": "Si. Busca el articulo en la lista, haz clic en el icono de la Caja e ingresa la cantidad a sumar (+) o restar (-). El ajuste queda registrado en el Historial de Movimientos con tu usuario y la fecha.",
            },
            {
                "q": "¿Que pasa al completar un ensamblaje?",
                "a": "El sistema ejecuta dos movimientos automaticos: resta los componentes usados de tu stock disponible y suma los kits terminados como productos listos para la venta.",
            },
        ],
    },
    "resources": {
        "id": "resources",
        "title": "Recursos para implementar, aprender y mejorar.",
        "description": "Accede a guias, plantillas y comparativas para tomar decisiones con menos incertidumbre.",
        "resource_groups": [
            {
                "title": "Guia de inicio",
                "items": ["Onboarding por modulo", "Checklist de migracion", "Primeros 30 dias"]
            },
            {
                "title": "Biblioteca operativa",
                "items": ["Plantillas de factura", "Politicas de cobranza", "Formatos de inventario"]
            },
            {
                "title": "Analisis y comparativas",
                "items": ["Majjun ERP vs opciones del mercado", "ROI operativo", "Casos de adopcion"]
            },
        ],
        "secondary_title": "Contenido por tema",
        "secondary_items": [
            "Facturacion y CFDI",
            "Compras y proveedores",
            "Inventarios y almacenes",
            "Finanzas para direccion",
            "Automatizacion con IA",
        ],
        "cta_label": "Explorar recursos",
        "cta_href": "/soporte/",
    },
    "pricing": {
        "id": "pricing",
        "eyebrow": "Pricing",
        "title": "Simple licenses, clear CFDI stamp packages.",
        "description": "Elige entre Plus y Premium, cambia mensual o anual, y agrega paquetes de timbres CFDI segun tu volumen.",
        "billing_periods": ["Mensual", "Anual"],
        "tabs": ["Monthly", "Annual"],
        "plan": "Premium",
        "price": "$80",
        "period": "/mo",
        "features": [
            "1 user included",
            "+ $80/mo per extra user",
            "For commercial businesses",
            "Minimum 5 users",
        ],
        "primary_cta": "Get started",
        "secondary_cta": "Contact sales",
        "plans": [
            {
                "name": "Plus",
                "tag": "For service businesses",
                "price": "$43",
                "period": "/mo",
                "featured": False,
                "cta": "Get started",
                "secondary_cta": "1 user included",
                "features": [
                    "+ $20/mo per extra user",
                    "For service businesses",
                    "Minimum 2 users",
                    "Core invoicing, finance and reports",
                ],
                "addons_title": "Includes:",
                "addons": ["CFDI ready", "Basic inventory", "AI assistant"],
            },
            {
                "name": "Premium",
                "tag": "Mas popular",
                "price": "$80",
                "period": "/mo",
                "featured": True,
                "cta": "Get started",
                "secondary_cta": "1 user included",
                "features": [
                    "+ $80/mo per extra user",
                    "For commercial businesses",
                    "Minimum 5 users",
                    "Procurement, inventory and audit trail",
                ],
                "addons_title": "Includes:",
                "addons": ["Advanced AI", "Full finance", "Priority onboarding"],
            },
        ],
        "stamp_title": "CFDI Stamps",
        "stamp_description": "Pay-as-you-go packages included with any plan.",
        "stamp_price": "$15",
        "stamp_period": "/mo",
        "stamps": [
            {"label": "100 stamps", "price": "$180"},
            {"label": "250 stamps", "price": "$390"},
            {"label": "500 stamps", "price": "$680"},
            {"label": "1,000 stamps", "price": "$1,200"},
            {"label": "2,000 stamps", "price": "$2,020"},
            {"label": "... up to 100k", "price": "Contact sales"},
        ],
        "notes": [
            "Annual billing saves you one full month of licenses.",
            "Licenses billed in MXN at the daily exchange rate.",
            "Prices in MXN. No discounts on stamp packs.",
        ],
    },
    "support": {
        "id": "support",
        "eyebrow": "Exito del cliente",
        "title": "Soporte que acompana la operacion completa.",
        "description": "Desde la implementacion hasta el uso diario, Majjun ERP te ayuda a resolver dudas funcionales, fiscales y operativas.",
        "pillars": [
            {"title": "Onboarding guiado", "description": "Configuracion inicial por modulo con objetivos por semana."},
            {"title": "Mesa de ayuda", "description": "Atencion para incidencias, dudas de uso y seguimiento de casos."},
            {"title": "Capacitacion continua", "description": "Sesiones por rol para ventas, finanzas, almacen y direccion."},
        ],
        "faqs": [
            "Cuanto tarda la implementacion inicial?",
            "Puedo migrar mis datos actuales?",
            "Que incluye el soporte postventa?",
            "Como funciona el acompañamiento fiscal CFDI 4.0?",
        ],
        "primary_cta": "Contactar soporte",
        "secondary_cta": "Agendar onboarding",
    },
    "clients": {
        "id": "stories",
        "title": "Why Majjun?",
        "description": "Majjun combina profundidad ERP con una experiencia clara para equipos que necesitan vender, timbrar, comprar, controlar inventario y reportar sin saltar entre sistemas.",
        "testimonials": [
            {"quote": "Facturacion, cobranza y reportes viven en el mismo flujo; el equipo ya no reconstruye informacion al cierre.", "author": "Finance lead"},
            {"quote": "La IA nos ayuda a crear borradores y revisar indicadores sin quitar aprobaciones del proceso.", "author": "Operations manager"},
            {"quote": "Compras e inventario quedaron conectados con evidencia clara de cada movimiento.", "author": "Commercial director"},
            {"quote": "Los paquetes de timbres y las licencias nos permiten crecer con costos visibles.", "author": "Founder"},
        ],
    },
}
